{% spaceless %}
<!DOCTYPE html>
<html lang="en">

<head>

	{% include 'Elements/Commons/HeaderInfo.phtml' %}
    <!-- Bootstrap Core CSS -->
    <link href="{{app.baseUrl}}vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="{{app.baseUrl}}vendor/metisMenu/metisMenu.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{{app.baseUrl}}dist/css/sb-admin-2.css" rel="stylesheet">
	
	<!-- Custom Fonts -->
    <link href="{{app.baseUrl}}vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
	
	<!-- jQuery -->
    <script src="{{app.baseUrl}}vendor/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{{app.baseUrl}}vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="{{app.baseUrl}}vendor/metisMenu/metisMenu.min.js"></script>

	
    <!-- Custom Theme JavaScript -->
    <script src="{{app.baseUrl}}dist/js/sb-admin-2.js"></script>
	
	{% set UrlRender = 'Helper_Assets'|loader('urlRender') %} 
	{{UrlRender|raw}}

</head>

<body>

    <div id="wrapper">
 		<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        {% include 'Elements/Commons/TopMenu.phtml' %}
		{% include 'Elements/Commons/LeftMenu.phtml' %}
		</nav>
        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="row">
        
						{{body|raw}}
              
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    

</body>

</html>

{% endspaceless %}