{% htmlcompress %}
<!DOCTYPE html>
<html lang="en">
<head>
	{% include 'Elements/Commons/HeaderInfo.phtml' %}
	 <meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="//fonts.googleapis.com/css?family=Love+Ya+Like+A+Sister" rel="stylesheet" type="text/css">
    <style>
        
        html {
            color: #888;
            display: table;
            height: 100%;
            text-align: center;
            width: 100%;
        }
        body {
			font-family: 'Love Ya Like A Sister', cursive;
            display: table-cell;
            vertical-align: middle;
            margin: 2em auto;
        }
        h1 {
            color: #06B506;
            font-size: 10em;
            font-weight: 400;
			margin: 0;
        }
        p {
            display: block;
			-webkit-margin-before: 1em;
			-webkit-margin-after: 1em;
			-webkit-margin-start: 0px;
			-webkit-margin-end: 0px;
			font-size: 5em;
			margin: 0;
        }
        @media only screen and (max-width: 380px) {
            body, p {
                width: 95%;
            }
            h1 {
                font-size: 5em;
                margin: 0 0 0.3em;
            }
			p {
           
			font-size: 2em;
        }
        }
    </style>
	
	<!-- javascript url render -->
	{% set UrlRender = 'Helper_Assets'|loader('urlRender') %} 
	{{UrlRender|raw}}
	
</head>
<body>

	<!-- Content area -->
	{{body|raw}}
	<!-- /content area -->

			
</body>
</html>
{% endhtmlcompress %}